sol_dex_dbt_models:               
  target: dev             
  outputs:
    dev:
      type: clickhouse
      schema: "{{ env_var('CLICKHOUSE_DEV_SCHEMA') }}"  
      host: "{{ env_var('CLICKHOUSE_DEV_HOST') }}"      
      port: "{{ env_var('CLICKHOUSE_DEV_PORT')| int }}"               
      user: "{{ env_var('CLICKHOUSE_DEV_USER') }}"         
      password: "{{ env_var('CLICKHOUSE_DEV_PASSWORD') }}" 
      threads: 4               
      secure: true

    prod:
      type: clickhouse
      schema: "{{ env_var('CLICKHOUSE_PROD_SCHEMA') }}"     
      host: "{{ env_var('CLICKHOUSE_PROD_HOST') }}"
      port: "{{ env_var('CLICKHOUSE_PROD_PORT') | int }}"
      user: "{{ env_var('CLICKHOUSE_PROD_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PROD_PASSWORD') }}"
      threads: 4
      secure: true