[project]
name = "chain-dbt-models"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dbt-clickhouse>=1.8.9",
    "dbt-core>=1.8.9",
    "sqlfluff>=3.4.0",
    "sqlfluff-templater-dbt>=3.4.0",
]
