name: Publish dbt Docs → GitHub Pages

on:
  workflow_run:
    workflows: ["dbt CI"]        # must match the CI workflow name
    branches:  [main]
    types:     [completed]

concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: read
  actions:  read                 
  pages:    write
  id-token: write

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    env:
      DBT_PROFILES_DIR: .
      CLICKHOUSE_PROD_PASSWORD: ${{ secrets.CLICKHOUSE_PROD_PASSWORD }}
      CLICKHOUSE_PROD_HOST:     ${{ secrets.CLICKHOUSE_PROD_HOST }}
      CLICKHOUSE_PROD_USER:     ${{ secrets.CLICKHOUSE_PROD_USER }}
      CLICKHOUSE_PROD_PORT:     ${{ secrets.CLICKHOUSE_PROD_PORT }}
      CLICKHOUSE_PROD_SCHEMA:   ${{ secrets.CLICKHOUSE_PROD_SCHEMA }}

    steps:
      - name: Download docs artifact from CI run
        uses: actions/download-artifact@v4
        with:
          name: dbt-docs
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}  

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dbt-docs

      - uses: actions/deploy-pages@v2
